### DISCUSSION TITLE
volume expansion

### DISCUSSION THREAD

**Discussion by speedkup** [sergelogvinov/proxmox-csi-plugin#160] [Q&A]
Hello, 

I would like to ask where can I enable volume expansion?

Thank you in advance for your answer.

**Comment by sergelogvinov** [comment]
Hi, it is always on.

https://kubernetes.io/blog/2022/05/05/volume-expansion-ga/  from 1.24 release.
You need to change storage size in PersistentVolumeClaim resource, and wait a ~10 second...

```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: myclaim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi <--- specify new size here
```
