### DISCUSSION TITLE
migration proxmox vm

### DISCUSSION THREAD

**Discussion by WMP** [sergelogvinov/proxmox-csi-plugin#169] [General]
Hello, with this CSI i can migrate proxmox VM with kubernetes to other node witl all CSI drivers based on ZFS?

**Comment by sergelogvinov** [comment]
Hello, the short answer - no.

* zfs is not a network file system, try to use ceph (for example).
* kubernetes way - is recreate the pods dying migration (not a VM). 
* Many options in kubernetes resources are immutable. You cannot change them after creation.

You can use zfs pvc/pv and migrate Pods between VM manually https://github.com/sergelogvinov/proxmox-csi-plugin/blob/main/docs/pvecsictl.md - it changes some pvc/pv options for you dying migration.

**Comment by Dragroth** [comment]
What about ZFS replication? If the volume is replicated to other zones, does it allow you to migrate the PV to another node, or do you have to do it manually via pvecsictl?

**Reply by sergelogvinov** [reply]
Hello, try this https://github.com/sergelogvinov/proxmox-csi-plugin/blob/main/docs/options.md 

```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
...
parameters:
  ## Optional: Zone replication
  replicate: "true"
  replicateSchedule: "*/15"
  replicateZones: "pve-1,pve-3"
```
