### ISSUE TITLE
Getting error in name resolution - but don't know from where 

### ISSUE THREAD

**Issue by markussiebert** [sergelogvinov/proxmox-csi-plugin#108]
## Bug Report

I see a lot of the following error:

```
 GRPC error: rpc error: code = Internal desc = 500 hostname lookup 'default' failed - failed to get address info for: default: Temporary failure in name resolution                                                                                                          │
│ csi-provisioner E1102 13:16:21.644338       1 capacity.go:551] CSI GetCapacity for {segment:0xc000712d80 storageClassName:proxmox-data-xfs}: rpc error: code = Internal desc = 500 hostname lookup 'default' failed - failed to get address info for: default: Temporary failure in name resolution                                          │
│ csi-provisioner W1102 13:16:21.644356       1 capacity.go:552] Retrying capacity.workItem{segment:(*topology.Segment)(0xc000712d80), storageClassName:"proxmox-data-xfs"} after 1 failures                                                                                                                                                   │
│ csi-provisioner I1102 13:16:21.644398       1 capacity.go:574] Capacity Controller: refreshing {segment:0xc000712d80 storageClassName:proxmox-data-xfs}                                                                                                            
````

my config looks like:

```
    config:
      clusters:
        - url: https://pve.redacted.de:8006/api2/json
          insecure: true
          token_id: "kubernetes-csi@pve!csi"
          token_secret: redacted
          region: default
    storageClass:
      - name: proxmox-data-xfs
        storage: vm-storage
        ssd: true
        cache: none
        reclaimPolicy: Delete
        fstype: xfs
```
### Description
I have no idea why 'default' will be looked up

### Logs
 see apove

### Environment

erver Version: v1.28.1 (Talos)

**Comment by sergelogvinov** [comment]
Hello,

```yaml
config:
      clusters:
        - url: https://pve.redacted.de:8006/api2/json
          insecure: true
          token_id: "kubernetes-csi@pve!csi"
          token_secret: redacted
          region: default
```

`region` is your proxmox node name.
You can get node list by command `pvecm nodes`

**Comment by sergelogvinov** [comment]
Oh, sorry,

region is your proxmox `cluster` name... It can be every thing...

**Comment by sergelogvinov** [comment]
So, what's the pod has such message - GRPC error: rpc error: code = Internal

**Comment by markussiebert** [comment]
trying your latest suggestions ...

**Comment by markussiebert** [comment]
Maybe I should describe my setup ... this is proxmox:
![image](https://github.com/sergelogvinov/proxmox-csi-plugin/assets/16692560/449f376b-96bc-428e-bffa-ba17dbff9859)
This is my k8s node:
```
 Name:               talos                                                                                                                                                                                                                                                                                                                     │
│ Roles:              control-plane                                                                                                                                                                                                                                                                                                             │
│ Labels:             beta.kubernetes.io/arch=amd64                                                                                                                                                                                                                                                                                             │
│                     beta.kubernetes.io/os=linux                                                                                                                                                                                                                                                                                               │
│                     kubernetes.io/arch=amd64                                                                                                                                                                                                                                                                                                  │
│                     kubernetes.io/hostname=talos                                                                                                                                                                                                                                                                                              │
│                     kubernetes.io/os=linux                                                                                                                                                                                                                                                                                                    │
│                     node-role.kubernetes.io/control-plane=                                                                                                                                                                                                                                                                                    │
│                     topology.kubernetes.io/region=pve-cluster                                                                                                                                                                                                                                                                                 │
│                     topology.kubernetes.io/zone=pve                                                                                                                                                                                                                                                                                           │
│ Annotations:        csi.volume.kubernetes.io/nodeid: {"csi.proxmox.sinextra.dev":"talos"}                                                                                                                                                                                                                                                     │
│                     node.alpha.kubernetes.io/ttl: 0                                                                                                                                                                                                                                                                                           │
│                     talos.dev/owned-labels: ["node-role.kubernetes.io/control-plane","topology.kubernetes.io/region","topology.kubernetes.io/zone"]   
```
And this my config at the moment:
```
    config:
      clusters:
        - url: https://pve.redacted.de:8006/api2/json
          insecure: true
          token_id: "kubernetes-csi@pve!csi"
          region: pve-cluster
    storageClass:
      - name: proxmox-data-xfs
        storage: vm-storage
        ssd: true
        cache: none
        reclaimPolicy: Delete
        fstype: xfs
```
