### ISSUE TITLE
ceph regional storage

### ISSUE THREAD

**Issue by WladyX** [sergelogvinov/proxmox-csi-plugin#123]
I have 3 proxmox nodes:
```
cube
tiny
tiny2
```

i have defined this sc:
```
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: proxmox-sc-ceph
parameters:
  csi.storage.k8s.io/fstype: ext4
  storage: ceph-pool
provisioner: csi.proxmox.sinextra.dev
reclaimPolicy: Delete
volumeBindingMode: Immediate
```

when i create a PVC, the PV gets bound to a node, not regional (i think):
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: foo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "proxmox-sc-ceph" # Empty string must be explicitly set otherwise default StorageClass will be set
  resources:
    requests:
      storage: 1Mi
```
```
❯ k describe pv pvc-5aea9ff4-6cb4-4431-b9db-057a98c5082f
Name:              pvc-5aea9ff4-6cb4-4431-b9db-057a98c5082f
Labels:            <none>
Annotations:       pv.kubernetes.io/provisioned-by: csi.proxmox.sinextra.dev
                   volume.kubernetes.io/provisioner-deletion-secret-name:
                   volume.kubernetes.io/provisioner-deletion-secret-namespace:
Finalizers:        [kubernetes.io/pv-protection]
StorageClass:      proxmox-sc-ceph
Status:            Bound
Claim:             default/foo-pvc
Reclaim Policy:    Delete
Access Modes:      RWO
VolumeMode:        Filesystem
Capacity:          1Gi
Node Affinity:
  Required Terms:
    Term 0:        topology.kubernetes.io/region in [prxcls]
Message:
Source:
    Type:              CSI (a Container Storage Interface (CSI) volume source)
    Driver:            csi.proxmox.sinextra.dev
    FSType:            ext4
    VolumeHandle:      prxcls/tiny/ceph-pool/vm-9999-pvc-5aea9ff4-6cb4-4431-b9db-057a98c5082f
    ReadOnly:          false
    VolumeAttributes:      storage=ceph-pool
                           storage.kubernetes.io/csiProvisionerIdentity=1703323894432-7509-csi.proxmox.sinextra.dev
Events:                <none>
```
my guess is that VolumeHandle should not include `tiny`, because for other PVC i get erorrs like
```
0s          Warning   FailedAttachVolume       pod/test-pod                                               AttachVolume.Attach failed for volume "pvc-a5764d29-8de7-4d5f-b907-6c91375000b8" : rpc error: code = InvalidArgument desc = volume prxcls/cube/ceph-pool/vm-9999-pvc-a5764d29-8de7-4d5f-b907-6c91375000b8 does not exist on the node k8s-wn2
```

am i doing something wrong? or is this a bug?
Thank you for this CSI and for your support!
