### ISSUE TITLE
shared storage HA question

### ISSUE THREAD

**Issue by WladyX** [sergelogvinov/proxmox-csi-plugin#134]
I have proxmox + ceph and i don't want to be bound to only one node.
Can i do something like:
```
# proxmox-csi.yaml
config:
  clusters:
    - url: https://cluster-api-1.exmple.com:8006/api2/json
      insecure: false
      token_id: "kubernetes-csi@pve!csi"
      token_secret: "secret"
      region: Region-1
    - url: https://cluster-api-2.exmple.com:8006/api2/json
      insecure: false
      token_id: "kubernetes-csi@pve!csi"
      token_secret: "secret"
      region: Region-1
```

So for Region-1 i would have HA.
Thanks
