### ISSUE TITLE
Migration between nodes

### ISSUE THREAD

**Issue by sbogomolov** [sergelogvinov/proxmox-csi-plugin#157]
We already support shared storage. However, PV backed by shared storage is bound to the node it was created on. If pod is killed and recreated on a different node - it cannot use that PV. Have anyone already looked into making this possible?

**Comment by sergelogvinov** [comment]
Hello,

shared storage is not properly tested. Because I do not have any of them.
There were some bugs, i do not remember when we fixed it.
But I heard it works now... 

Please, try latest release (or edge).
We have a plan to make refactoring and add more tests of shared storages in future releases.

PS. Scheduler is responsible for migration of pods. IF it happens => PVC has right affinity already. Probably the issue in another component of proxmox/kubernetes. Try to check the logs.

**Comment by sbogomolov** [comment]
When pod migrates to a different node we would need to detach the virtual disk from one VM and attach it to another one. Are you saying that this logic is already there?

**Comment by taylor-madeak** [comment]
@sbogomolov I just tested this in my homelab and can verify that this CSI driver will detach the volume and re-attach it on the appropriate node when the scheduler migrates the pod to a different node.  This is fairly straightforward to test by just cordoning the node and restarting the pod.

**Comment by sbogomolov** [comment]
> @sbogomolov I just tested this in my homelab and can verify that this CSI driver will detach the volume and re-attach it on the appropriate node when the scheduler migrates the pod to a different node.  This is fairly straightforward to test by just cordoning the node and restarting the pod.

This is great news! I'll try to test this on my cluster.

**Comment by vehagn** [comment]
@taylor-madeak @christiaangoossens Could you please provide more details on how you got volume migration to work?

I've tried both `v0.6.1` and `edge` and can't get volume migration to work across zones/hypervisor host machines. 

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://raw.githubusercontent.com/sergelogvinov/proxmox-csi-plugin/v0.6.1/docs/deploy/proxmox-csi-plugin-release.yml
  - proxmox-csi-secret.yaml
  - sc.yaml

images:
  - name: ghcr.io/sergelogvinov/proxmox-csi-node
    newTag: edge
  - name: ghcr.io/sergelogvinov/proxmox-csi-controller
    newTag: edge
```

with the following `StorageClass`

```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: proxmox-csi
allowVolumeExpansion: true
parameters:
  csi.storage.k8s.io/fstype: ext4
  storage: local-zfs
  cache: writethrough
  ssd: "true"
mountOptions:
  - noatime
provisioner: csi.proxmox.sinextra.dev
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
```

I've tried with both a `StatefulSet`

```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: stateful
  namespace: pve-csi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stateful-pv
  template:
    metadata:
      labels:
        app: stateful-pv
    spec:
      containers:
        - name: alpine
          image: alpine
          command: [ "sleep","1d" ]
          volumeMounts:
            - name: stateful
              mountPath: /mnt
  volumeClaimTemplates:
     - metadata:
         name: stateful
       spec:
         storageClassName: proxmox-csi
         accessModes: [ "ReadWriteOnce" ]
         resources:
           requests:
             storage: 3Gi
  serviceName: stateful
```

and a `Deployment` with an ephemeral volume (this alone works, but the data is of course lost on each restart of the pod) and a `pvc`

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pv-deploy
  namespace: pve-csi
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 0
  selector:
    matchLabels:
      app: pv-deploy
  template:
    metadata:
      labels:
        app: pv-deploy
    spec:
      containers:
        - name: alpine
          image: alpine
          command: [ "sleep","1d" ]
          volumeMounts:
            - name: deploy
              mountPath: /mnt
            - name: pvc
              mountPath: /tmp
      volumes:
        - name: pvc
          persistentVolumeClaim:
            claimName: pvc
        - name: deploy
          ephemeral:
            volumeClaimTemplate:
              spec:
                storageClassName: proxmox-csi
                accessModes: [ "ReadWriteOnce" ]
                resources:
                  requests:
                    storage: 1.5Gi
```

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc
  namespace: pve-csi
spec:
  storageClassName: proxmox-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
```

I've tried both changing `nodeAffinity` and cordoning the node the pods are running on before restarting them.

I'm running a three node Proxmox cluster (`homelab` with machines `abel`, `cantor`, and `euclid`) running Kubernetes in two separate VMs , each on their own physical node (`k8s-ctrl-01` on `abel` and `k8s-ctrl-02` on `euclid`).

The k8s-nodes are manually labelled

```shell
kubectl label node k8s-ctrl-01 topology.kubernetes.io/region=homelab
kubectl label node k8s-ctrl-01 topology.kubernetes.io/zone=abel

kubectl label node k8s-ctrl-02 topology.kubernetes.io/region=homelab
kubectl label node k8s-ctrl-02 topology.kubernetes.io/zone=euclid
```

Migrating `k8s-ctrl-02` to `abel` (so that both VMs are on the same physical host/zone) and relabelling it

```shell
kubectl label node k8s-ctrl-02 topology.kubernetes.io/zone=abel --overwrite
```

The PVs are migrated flawlessly from one node to the other and back again.

I see in the [README.md](https://github.com/sergelogvinov/proxmox-csi-plugin/blob/76c899e4e1c8f2287854a4e08fbbdd8a1c7360a9/README.md?plain=1#L30) that

> The Pod `cannot` migrate to another zone (another Proxmox node)

but the above comments led me to believe that a pod **is** able to migrate to another zone/hypervisor host machine.

Am I doing something wrong, or is pv-migration to a different zone not supported yet? If no, is it a planned feature?

I'm nevertheless impressed by this plugin and I'm going to make good use of it in my homelab!

**Comment by sergelogvinov** [comment]
Hi, local storages cannot migrate to another proxmox node. It works only with `shared` storages like ceph.

But you can migrate pv/pvc to another node manually, https://github.com/sergelogvinov/proxmox-csi-plugin/blob/main/docs/pvecsictl.md brew version has a bug, try edge version...

```
docker pull ghcr.io/sergelogvinov/pvecsictl:edge
```

**Comment by vehagn** [comment]
@sergelogvinov Awesome! I'll have to try it.

Would it be possible to port this functionality to proxmox-csi-plugin?

**Comment by sergelogvinov** [comment]
It is not easy to implement this. There are many limitations on the Kubernetes side. That's why I created this CLI tool. We cannot share with the Kubernetes scheduler the cost of launching pods on a non-local Proxmox node.

**Comment by veebkolm** [comment]
I'm trying to use a nfs storage, at least being bound to a certain node. However it seems that the CSI disallows any kind of NFS storage?

**Comment by sergelogvinov** [comment]
> I'm trying to use a nfs storage, at least being bound to a certain node. However it seems that the CSI disallows any kind of NFS storage?

Hi @veebkolm, I haven't tested many shared storage options. I know that CIFS works well, but Samba (cifs) isn't fully reliable. NFS is made for network file systems, not for block devices. If you can test storing raw/qcow disks on NFS storage and it works fine, we can remove this limitation.

https://github.com/sergelogvinov/proxmox-csi-plugin/blob/cbcb65fc19841258a94db7b4d21b06c492b2a376/pkg/csi/controller.go#L182-L185

thanks.

**Comment by veebkolm** [comment]
Hi, @sergelogvinov 

We hold most of our VM disks on a separate machine, served as raw images over nfs, works very fine

![image](https://github.com/user-attachments/assets/83f1564d-3614-416a-a9b0-dc6d0fed5b2a)

**Comment by veebkolm** [comment]
@sergelogvinov I tested it out, everything seems to work, including rescheduling and mounting on another node :+1: 

Thanks!

**Comment by christiaangoossens** [comment]
@veebkolm Did you also test scenarios that NFS is normally known to have some issues with? I am not an expert with how raw disks are written back to storage in Proxmox, but I had some issues with VM boot disks on NFS (Truenas). Didn't have any with iSCSI, although it's much more annoying to set up.

Might be good to test some heavy random read write and databases.

**Comment by veebkolm** [comment]
Good point - I didn't yet try any real, heavy workloads. I will try to post an update when we do.

As for background, the NAS we're using is an vanilla Ubuntu machine having a ZFS pool - so ZFS/NFS related caveats are valid like with Truenas. We haven't had problems with our VM boot disks but I suppose there haven't been much storage intensive workloads.

**Comment by lknite** [comment]
Am working to get setup for the first time using proxmox clusterapi provider and later proxmox csi plugin with ceph storge.  The csi homepage at github doesn't mention ceph or that it works when moving pods around.  After reading this issue it sounds like it is going to work.  I'll update here once I've had a chance to test.  If so, might be time to update the main page.

**Comment by sergelogvinov** [comment]
New capability: ZFS storage with replication parameters. Available in the edge version or v0.11.0.

```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: proxmox-storage-class-name

parameters:
  storage: zfs-storage-name

  ## Optional: Zone replication
  replicate: "true"
  replicateSchedule: "*/15"
  # nodes for zfs replication
  replicateZones: "pve-1,pve-3"

provisioner: csi.proxmox.sinextra.dev
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer|Immediate
```
