### ISSUE TITLE
Ability to attach disks on virtio bus

### ISSUE THREAD

**Issue by kowalski7cc** [sergelogvinov/proxmox-csi-plugin#182]
## Feature Request

Ability to configure storageClass to attach disks to virtio instead of scsi bus on proxmox.

![image](https://github.com/sergelogvinov/proxmox-csi-plugin/assets/5065094/a4364af1-36e2-485b-978a-b1d31e8745bd)

### Description

A new configuration could be like this

```yaml
storageClass:
  - name: proxmox-fast-xfs
    storage: fast
    reclaimPolicy: Delete
    fstype: xfs
    bus: virtio
```

Thanks!
