### ISSUE TITLE
No Proxmox Clusters Found

### ISSUE THREAD

**Issue by dnviti** [sergelogvinov/proxmox-csi-plugin#233]
## Bug Report
CSI plugin is unable to start due to the inability to properly read ClustersConfig

### Description
Whilst i've created the correct config file following the documentation, the plugin is not able to read clusters list from configuration
```yaml
# proxmox-csi.yaml
config:
  clusters:
    - url: https://my-pve.domain.com/api2/json
      insecure: false
      username: "kubernetes-csi@pve!csi"
      password: "token"
      region: pvecluster01

storageClass:
  - name: proxmox-data-xfs
    storage: pvepool01
    reclaimPolicy: Delete
    fstype: xfs
  - name: proxmox-data
    storage: pvepool01
    reclaimPolicy: Delete
    fstype: ext4
    cache: writethrough
```

I've found that the check which fails seems to resides in this particular function
```go
// NewCluster creates a new Proxmox cluster client.
func NewCluster(config *ClustersConfig, hclient *http.Client) (*Cluster, error) {
	clusters := len(config.Clusters)
	if clusters > 0 {
		proxmox := make(map[string]*pxapi.Client, clusters)

		for _, cfg := range config.Clusters {
			tlsconf := &tls.Config{InsecureSkipVerify: true}
			if !cfg.Insecure {
				tlsconf = nil
			}

			client, err := pxapi.NewClient(cfg.URL, hclient, os.Getenv("PM_HTTP_HEADERS"), tlsconf, "", 600)
			if err != nil {
				return nil, err
			}

			if cfg.Username != "" && cfg.Password != "" {
				if err := client.Login(cfg.Username, cfg.Password, ""); err != nil {
					return nil, err
				}
			} else {
				client.SetAPIToken(cfg.TokenID, cfg.TokenSecret)
			}

			proxmox[cfg.Region] = client
		}

		return &Cluster{
			config:  config,
			proxmox: proxmox,
		}, nil
	}

	return nil, fmt.Errorf("no Proxmox clusters found")
}
```

`clusters := len(config.Clusters)` returns 0.

### Logs
[main.go:107] Failed to create controller service: failed to create proxmox cluster client: no Proxmox clusters found

Controller: [`kubectl logs -c proxmox-csi-plugin-controller proxmox-csi-plugin-controller-...`]

Node: [`kubectl logs -c proxmox-csi-plugin-node proxmox-csi-plugin-node-...`]

### Environment

- Plugin version: latest
- Kubernetes version: [`kubectl version --short`] 1.29
- CSI capasity: [`kubectl get csistoragecapacities -ocustom-columns=CLASS:.storageClassName,AVAIL:.capacity,ZONE:.nodeTopology.matchLabels -A`]
- CSI resource on the node: [`kubectl get CSINode <node> -oyaml`]
- Node describe: [`kubectl describe node <node>`]
- OS version [`cat /etc/os-release`]

**Comment by sergelogvinov** [comment]
Hi, this config works for helm chart values.

It stores as configmap:

```yaml
clusters:
    - url: https://my-pve.domain.com/api2/json
      insecure: false
      username: "kubernetes-csi@pve!csi"
      password: "token"
      region: pvecluster01
```
