### ISSUE TITLE
Snapshot support

### ISSUE THREAD

**Issue by ColonelBundy** [sergelogvinov/proxmox-csi-plugin#247]
### Description
Any chance of implementing snapshot support?

**Comment by sergelogvinov** [comment]
Hi, currently I do not think so https://bugzilla.proxmox.com/show_bug.cgi?id=5489

**Comment by ColonelBundy** [comment]
While there's currently no way to do this using the api, an agent installed on each pve host could be a middle ground. However, this comes with it's own set of challenges.

**Comment by sergelogvinov** [comment]
Yeah, and probably to make the solution (backend changes) to the proxmox api much better... But it required a time too.

So, i decided to wait a few month first.

**Comment by sergelogvinov** [comment]
The `edge` version can make a snapshots now. see limitations https://github.com/sergelogvinov/proxmox-csi-plugin/blob/main/docs/volumesnapshot.md

Do not forget to run snapshotter as sidecar + apply CRDs and separate deployment (example: https://github.com/sergelogvinov/gitops-examples/tree/main/apps/clouds/csi-snapshotter)

Helm chart values:

```yaml
controller:
  plugin:
    image:
      pullPolicy: Always
      tag: edge
  snapshotter:
    enabled: true

node:
  plugin:
    image:
      pullPolicy: Always
      tag: edge
```

**Comment by gianvetter** [comment]
I deployed the snapshot controller and the CSI using Edge images. For some reason, the CSI will not create the snapshot because the node name is missing from the post URL of the API command. The zone and region labels are on the nodes using your Proxmox cloud controller :). Do you have any ideas? Please let me know if you need more information. 

```
Error:
    Message:     Failed to check and update snapshot content: failed to take snapshot of the volume PVE-Cluster-01//nvme-zfs/vm-10010-pvc-ad05b1e1-2021-4db6-af5c-7dbe7bd9e9c8: "rpc error: code = Internal desc = failed to copy pvc: 501 Method 'POST /nodes//storage/nvme-zfs/content/vm-10010-pvc-ad05b1e1-2021-4db6-af5c-7dbe7bd9e9c8' not implemented, vmParams=map[node: target:vm-10010-snapshot-b777fa2b-3497-454b-97f4-e16d663898bc target_node:PVE-Node-02 volume:vm-10010-pvc-ad05b1e1-2021-4db6-af5c-7dbe7bd9e9c8]"
```

CSI Deployment via HelmChart
```
existingConfigSecret: proxmox-csi-secret
existingConfigSecretKey: config.yml
storageClass:
  - name: block-ssd
    storage: nvme-zfs
    reclaimPolicy: Delete
    fstype: ext4
    extraParameters:
      replicate: 'true'
      replicateSchedule: "*/15"
      replicateZones: "PVE-Node-01,PVE-Node-02"
controller:
  plugin:
    image:
      pullPolicy: Always
      tag: edge
  snapshotter:
    enabled: true
node:
  plugin:
    image:
      pullPolicy: Always
      tag: edge
```

**Comment by RuTHlessBEat200** [comment]
I have another error
`Failed to create snapshot: failed to take snapshot of the volume proxmox/proxmox01/data/9999/vm-9999-pvc-67f209cd-8170-43fb-84dd-e57668d2d23f.raw: "rpc error: code = Internal desc = unable to parse directory volume name 'vm-9999-snapshot-4a50b134-d6d3-4f54-ac2e-4b9146095065'"`

Cluster info:

- PVE 9.0.11
- PVE cluster name: proxmox
- PVE node: proxmox01 (all k8s nodes are on this node)
- Talos 1.11.2
- k8s v1.34.1

Information to replicate the error:

1. Add a directory in Proxmox under storage, in my case "data"
2. Add the labels on nodes
```
topology.kubernetes.io/region=proxmox
topology.kubernetes.io/zone=proxmox01
```
3. Deploy csi with Helm Chart (I use ArgoCD)
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: proxmox-csi
  namespace: argocd
spec:
  project: default
  source:
    repoURL: ghcr.io/sergelogvinov/charts
    chart: proxmox-csi-plugin
    targetRevision: 0.4.0
    helm:
      values: |
        config:
          clusters:
          - url: https://proxmox.yourdomain.com:443/api2/json
            insecure: false
            # For snapshot support, you need to use root@pam instead of token
            username: root@pam
            password: ""
            region: proxmox #PVE cluster name, yes I was very creative with the naming
        storageClass:
          - name: proxmox-data-hdd
            storage: data
            reclaimPolicy: Delete
            fstype: ext4
          - name: proxmox-data-ssd
            storage: ssd
            reclaimPolicy: Delete
            fstype: ext4
            mountOptions:
              - discard
        metrics:
          enabled: true
        timeout: 2m
        controller:
          plugin:
            image:
              pullPolicy: Always
              tag: edge
          snapshotter:
            enabled: true

        node:
          plugin:
            image:
              pullPolicy: Always
              tag: edge
  destination:
    server: https://kubernetes.default.svc
    namespace: proxmox-csi
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
```
Deploy these crd
```
k apply -f https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/v8.2.0/client/config/crd/snapshot.storage.k8s.io_volumesnapshotclasses.yaml
k apply -f https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/v8.2.0/client/config/crd/snapshot.storage.k8s.io_volumesnapshotcontents.yaml
k apply -f https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/v8.2.0/client/config/crd/snapshot.storage.k8s.io_volumesnapshots.yaml
```
Create VolumeSnapshotClass

```
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: proxmox-snapshots
parameters:
  # Optional: specify zone to copy snapshots in a specific zone
  zone: proxmox01
driver: csi.proxmox.sinextra.dev
deletionPolicy: Delete
```
Find a pvc that uses this csi
```
k get pvc data-keycloak-postgresql-0
NAME                         STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS       VOLUMEATTRIBUTESCLASS   AGE
data-keycloak-postgresql-0   Bound    pvc-67f209cd-8170-43fb-84dd-e57668d2d23f   8Gi        RWO            proxmox-data-hdd   <unset>                 93d
```

Try to create a VolumeSnapshot
```
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: test-proxmox-snapshot
  namespace: keycloak
spec:
  volumeSnapshotClassName: proxmox-snapshots
  source:
    persistentVolumeClaimName: data-keycloak-postgresql-0
```
Describe the VolumeSnapshot

```
 k describe volumesnapshot test-proxmox-snapshot
Name:         test-proxmox-snapshot
Namespace:    keycloak
Labels:       <none>
Annotations:  <none>
API Version:  snapshot.storage.k8s.io/v1
Kind:         VolumeSnapshot
Metadata:
  Creation Timestamp:  2025-11-04T22:36:15Z
  Finalizers:
    snapshot.storage.kubernetes.io/volumesnapshot-as-source-protection
    snapshot.storage.kubernetes.io/volumesnapshot-bound-protection
  Generation:        1
  Resource Version:  94849994
  UID:               4a50b134-d6d3-4f54-ac2e-4b9146095065
Spec:
  Source:
    Persistent Volume Claim Name:  data-keycloak-postgresql-0
  Volume Snapshot Class Name:      proxmox-snapshots
Status:
  Bound Volume Snapshot Content Name:  snapcontent-4a50b134-d6d3-4f54-ac2e-4b9146095065
  Error:
    Message:     Failed to create snapshot: failed to take snapshot of the volume proxmox/proxmox01/data/9999/vm-9999-pvc-67f209cd-8170-43fb-84dd-e57668d2d23f.raw: "rpc error: code = Internal desc = unable to parse directory volume name 'vm-9999-snapshot-4a50b134-d6d3-4f54-ac2e-4b9146095065'"
    Time:        2025-11-04T22:36:24Z
  Ready To Use:  false
Events:
  Type    Reason            Age   From                 Message
  ----    ------            ----  ----                 -------
  Normal  CreatingSnapshot  7s    snapshot-controller  Waiting for a snapshot keycloak/test-proxmox-snapshot to be created by the CSI driver.
```

In Proxmox I see this error

```
DEBUG: starting worker UPID:proxmox01:0016B058:09FD0868:690A801F:imgcopy::root@pam:
TASK ERROR: unable to parse directory volume name 'vm-9999-snapshot-4a50b134-d6d3-4f54-ac2e-4b9146095065'
```
