### ISSUE TITLE
Upgrade to v0.8.1 breaks encryption

### ISSUE THREAD

**Issue by camaeel** [sergelogvinov/proxmox-csi-plugin#261]
### Description

1. I had installed version 0.7.0 of proxmox CSI plugin. LUKS encryption was enabled.
2. I created some volumes
3. Then I upgraded to v0.8.1.
4. After upgrading, restart of pods which used PVCs provided by this CSI plugin failed due to:
    ```
    0s          Warning   FailedMount              pod/loki-0         MountVolume.MountDevice failed for volume "pvc-398cb20e-1ba2-47c9-8b49-c758c9480045" : rpc error: code = Internal desc = encryption key rejected
    ```

### Logs

If needed I can perfom the upgrade again.

Controller: [`kubectl logs -c proxmox-csi-plugin-controller proxmox-csi-plugin-controller-...`]

Node: [`kubectl logs -c proxmox-csi-plugin-node proxmox-csi-plugin-node-...`]

### Environment

- Plugin version: v0.8.1
- Kubernetes version: v1.30.5
- CSI capasity: 
```
CLASS                    AVAIL           ZONE
proxmox-data-ephemeral   1581234508740   map[topology.kubernetes.io/region:homelab-proxmox-1 topology.kubernetes.io/zone:osiris]
proxmox-data             1581234508740   map[topology.kubernetes.io/region:homelab-proxmox-1 topology.kubernetes.io/zone:osiris]
```
- CSI resource on the node: [`kubectl get CSINode <node> -oyaml`]
- Node describe: [`kubectl describe node <node>`]
- OS version: Talos 1.8.0

### Community Note

* Please vote on this issue by adding a 👍 reaction to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request

**Comment by sergelogvinov** [comment]
Thank you for bug report. 

I've checked creating new pvc on latest version - everything work ok.  I need to check the different version...

**Comment by camaeel** [comment]
I think this might happen only to "migration" scenario.

**Comment by sergelogvinov** [comment]
Hi, I released v0.8.2 i found the bug #262. 
Also, unfortunately PV secrets can inadvertently appear in the logs, posing a potential security risk

**Comment by camaeel** [comment]
Log from v0.8.3:

```
proxmox-csi-node-msjlh proxmox-csi-node I0929 19:28:27.921725       1 node.go:521] "NodeGetCapabilities: called"
proxmox-csi-node-msjlh proxmox-csi-node I0929 19:28:27.928527       1 node.go:521] "NodeGetCapabilities: called"
proxmox-csi-node-msjlh proxmox-csi-node I0929 19:28:27.929136       1 node.go:521] "NodeGetCapabilities: called"
proxmox-csi-node-msjlh proxmox-csi-node I0929 19:28:27.929810       1 node.go:92] "NodeStageVolume: called" args="{\"publish_context\":{\"DevicePath\":\"/dev/disk/by-id/wwn-0x5056432d49443033\",\"lun\":\"3\"},\"secrets\":\"***stripped***\",\"staging_target_path\":\"/var/lib/kubelet/plugins/kubernetes.io/csi/csi.proxmox.sinextra.dev/b5d00812b9ff38d8e032d351e8dac99d9e0fd3d7cf998ed96327064cb86f85a5/globalmount\",\"volume_capability\":{\"AccessType\":{\"Mount\":{\"fs_type\":\"ext4\",\"mount_flags\":[\"discard\"]}},\"access_mode\":{\"mode\":1}},\"volume_context\":{\"cache\":\"none\",\"ssd\":\"true\",\"storage\":\"local-lvm\",\"storage.kubernetes.io/csiProvisionerIdentity\":\"1708632090030-452-csi.proxmox.sinextra.dev\"},\"volume_id\":\"homelab-proxmox-1/osiris/local-lvm/vm-9999-pvc-a18d22ab-a369-4ea5-8315-d51a045d6323\"}"
proxmox-csi-node-msjlh proxmox-csi-node I0929 19:28:27.930142       1 node.go:127] "NodeStageVolume: mount device" device="/dev/sdc" path="/var/lib/kubelet/plugins/kubernetes.io/csi/csi.proxmox.sinextra.dev/b5d00812b9ff38d8e032d351e8dac99d9e0fd3d7cf998ed96327064cb86f85a5/globalmount"
proxmox-csi-node-msjlh proxmox-csi-node I0929 19:28:27.930165       1 node.go:181] "NodeStageVolume: volume is encrypted" device="/dev/sdc"
proxmox-csi-node-msjlh proxmox-csi-node E0929 19:28:29.770508       1 node.go:201] "NodeStageVolume: failed to open encrypted device" err="encryption key rejected" device="/dev/sdc"
proxmox-csi-node-msjlh proxmox-csi-node E0929 19:28:29.770531       1 main.go:122] GRPC error: rpc error: code = Internal desc = encryption key rejected
```

**Comment by sergelogvinov** [comment]
I think better to migrate to new version.

1. deploy old csi-plugin
2. scale up the `kubectl statefulset loki --replicas=1` to get one copy of loki and the PVC can be unencrypted 
3. upgrade the csi-plugin to lates
4. update the encrypted secret
5. scale up the loki to 2 pods `kubectl statefulset loki --replicas=2` (make sure that all PVC allocated in one proxmox node), now you have two PVC in one proxmox node, new one has new secrets key
6. scale down `kubectl statefulset loki --replicas=1` to one copy
7. deploy rsync pod with two attached PVC
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: debian
  namespace: kube-system
spec:
  containers:
  - image: debian
    command:
      - sleep
      - "14d"
    name: debian
    resources:
      limits:
        memory: "4Gi"
      requests:
        cpu: "100m"
        memory: "128Mi"
    securityContext:
      privileged: true
    volumeMounts:
    - name: src
      mountPath: /mnt/src
    - name: dst
      mountPath: /mnt/dst
  priorityClassName: system-node-critical
  tolerations:
    - operator: Exists
    - key: node.kubernetes.io/disk-pressure
      operator: Exists
      effect: NoSchedule
  volumes:
    - name: src
      persistentVolumeClaim:
        claimName: data-loki-0
    - name: dst
      persistentVolumeClaim:
        claimName: data-loki-1
```
9. rsync data `rsync -av --delete /mnt/src/ /mnt/dst/`
10. scale down loki `kubectl statefulset loki --replicas=0`, rsync again, and delete "rsync" pod
11. swap PVCs `pvecsictl swap data-loki-0 data-loki-1` tool documentation [pvecsictl](docs/pvecsictl.md)
12. scale up loki `kubectl statefulset loki --replicas=1`
13. check the data
14. delete old block device `kubectl delete pvc data-loki-1` do not forget delete pv too.
