### ISSUE TITLE
[Talos 1.8.0] Proxmox CCM labelled nodes do not start daemonset, and can't partition disks

### ISSUE THREAD

**Issue by ccureau** [sergelogvinov/proxmox-csi-plugin#267]
### Description

I set up a new Talos 1.8.0 cluster with the `proxmox-csi-plugin` manifest included. I then installed the Proxmox Cloud Config Manager. No PVCs could be created.

The reason for this is that even though CCM properly labelled the nodes, the CSI `DaemonSet` is looking for the label `node.cloudprovider.kubernetes.io/platform=nocloud`, which is not attached to any of the nodes.

After adding the appropriate label to a node, the `proxmox-csi-plugin-node` pod started, and I was able to provision a PVC.

As I've successfully gotten PVCs on my `talos-node-1` node, I have pasted logs specific to `talos-node-2`, which does not have the label.

### Logs

No specific errors were shown in the controller, which made it difficult to diagnose.

Since the node wasn't running, I could get no logs.

### Environment

- Plugin version: `v0.8.2`
- Kubernetes version:
```
Client Version: v1.31.1
Kustomize Version: v5.4.2
Server Version: v1.30.5
```
- CSI capacity: 
```
CLASS              AVAIL        ZONE
proxmox-data-xfs   0            map[topology.kubernetes.io/region:dell-cluster topology.kubernetes.io/zone:r720]
standard           56820460Ki   map[topology.kubernetes.io/region:dell-cluster topology.kubernetes.io/zone:r720]
proxmox-data       0            map[topology.kubernetes.io/region:dell-cluster topology.kubernetes.io/zone:r720]
```
- CSI resource on the node:
```
apiVersion: storage.k8s.io/v1
kind: CSINode
metadata:
  annotations:
    storage.alpha.kubernetes.io/migrated-plugins: kubernetes.io/aws-ebs,kubernetes.io/azure-disk,kubernetes.io/azure-file,kubernetes.io/cinder,kubernetes.io/gce-pd,kubernetes.io/vsphere-volume
  creationTimestamp: "2024-10-05T15:09:31Z"
  name: talos-node-2
  ownerReferences:
  - apiVersion: v1
    kind: Node
    name: talos-node-2
    uid: 2977e4cf-148e-4af3-b8c3-b0329ab6041c
  resourceVersion: "10522"
  uid: 9bfd75d7-4f16-4752-939b-daef4beb6df1
spec:
  drivers: null
```
- Node describe:
```
Name:               talos-node-2
Roles:              <none>
Labels:             beta.kubernetes.io/arch=amd64
                    beta.kubernetes.io/instance-type=24VCPU-32GB
                    beta.kubernetes.io/os=linux
                    extensions.talos.dev/iscsi-tools=v0.1.5
                    extensions.talos.dev/qemu-guest-agent=9.1.0
                    failure-domain.beta.kubernetes.io/region=dell-cluster
                    failure-domain.beta.kubernetes.io/zone=r720
                    kubernetes.io/arch=amd64
                    kubernetes.io/hostname=talos-node-2
                    kubernetes.io/os=linux
                    node.kubernetes.io/instance-type=24VCPU-32GB
                    topology.kubernetes.io/region=dell-cluster
                    topology.kubernetes.io/zone=r720
Annotations:        alpha.kubernetes.io/provided-node-ip: 192.168.100.122
                    extensions.talos.dev/schematic: dc7b152cb3ea99b821fcb7340ce7168313ce393d663740b791c36f6e95fc8586
                    flannel.alpha.coreos.com/backend-data: {"VNI":1,"VtepMAC":"1a:12:bd:c0:1b:ac"}
                    flannel.alpha.coreos.com/backend-type: vxlan
                    flannel.alpha.coreos.com/kube-subnet-manager: true
                    flannel.alpha.coreos.com/public-ip: 192.168.100.122
                    node.alpha.kubernetes.io/ttl: 0
                    talos.dev/owned-annotations: ["extensions.talos.dev/schematic"]
                    talos.dev/owned-labels: ["extensions.talos.dev/iscsi-tools","extensions.talos.dev/qemu-guest-agent"]
                    volumes.kubernetes.io/controller-managed-attach-detach: true
CreationTimestamp:  Sat, 05 Oct 2024 15:09:30 +0000
Taints:             <none>
Unschedulable:      false
Lease:
  HolderIdentity:  talos-node-2
  AcquireTime:     <unset>
  RenewTime:       Sat, 05 Oct 2024 21:58:38 +0000
Conditions:
  Type                 Status  LastHeartbeatTime                 LastTransitionTime                Reason                       Message
  ----                 ------  -----------------                 ------------------                ------                       -------
  NetworkUnavailable   False   Sat, 05 Oct 2024 15:09:54 +0000   Sat, 05 Oct 2024 15:09:54 +0000   FlannelIsUp                  Flannel is running on this node
  MemoryPressure       False   Sat, 05 Oct 2024 21:58:20 +0000   Sat, 05 Oct 2024 15:09:30 +0000   KubeletHasSufficientMemory   kubelet has sufficient memory available
  DiskPressure         False   Sat, 05 Oct 2024 21:58:20 +0000   Sat, 05 Oct 2024 15:09:30 +0000   KubeletHasNoDiskPressure     kubelet has no disk pressure
  PIDPressure          False   Sat, 05 Oct 2024 21:58:20 +0000   Sat, 05 Oct 2024 15:09:30 +0000   KubeletHasSufficientPID      kubelet has sufficient PID available
  Ready                True    Sat, 05 Oct 2024 21:58:20 +0000   Sat, 05 Oct 2024 15:09:51 +0000   KubeletReady                 kubelet is posting ready status
Addresses:
  InternalIP:  192.168.100.122
  Hostname:    talos-node-2
Capacity:
  cpu:                24
  ephemeral-storage:  101132Mi
  hugepages-2Mi:      0
  memory:             32846116Ki
  pods:               110
Allocatable:
  cpu:                23950m
  ephemeral-storage:  95171693615
  hugepages-2Mi:      0
  memory:             32350500Ki
  pods:               110
System Info:
  Machine ID:                 34f5260c737f99d4c5b780b9438c370d
  System UUID:                ba35a67e-2648-4139-b6e0-465de8b19c6e
  Boot ID:                    a3a58fc9-d4f7-4842-9482-2c316d52db98
  Kernel Version:             6.6.52-talos
  OS Image:                   Talos (v1.8.0)
  Operating System:           linux
  Architecture:               amd64
  Container Runtime Version:  containerd://2.0.0-rc.4
  Kubelet Version:            v1.30.5
  Kube-Proxy Version:         v1.30.5
PodCIDR:                      10.244.3.0/24
PodCIDRs:                     10.244.3.0/24
ProviderID:                   proxmox://dell-cluster/1222
Non-terminated Pods:          (2 in total)
  Namespace                   Name                  CPU Requests  CPU Limits  Memory Requests  Memory Limits  Age
  ---------                   ----                  ------------  ----------  ---------------  -------------  ---
  kube-system                 kube-flannel-gqs6k    100m (0%)     0 (0%)      50Mi (0%)        0 (0%)         6h49m
  kube-system                 kube-proxy-2qkxp      0 (0%)        0 (0%)      0 (0%)           0 (0%)         6h49m
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource           Requests   Limits
  --------           --------   ------
  cpu                100m (0%)  0 (0%)
  memory             50Mi (0%)  0 (0%)
  ephemeral-storage  0 (0%)     0 (0%)
  hugepages-2Mi      0 (0%)     0 (0%)
Events:              <none>
```
- OS version: Talos 1.8.0

### Community Note

* Please vote on this issue by adding a 👍 reaction to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request

**Comment by sergelogvinov** [comment]
Hello, thank you for the feedback. 

Could you please share the details on how you installed the plugin?

Thanks.

**Comment by ccureau** [comment]
> Could you please share the details on how you installed the plugin?

Sure!

First, I installed Talos and bootstrapped the proxmox-csi-plugin manifest as the page suggests:
```
cluster:
  externalCloudProvider:
    enabled: true
    manifests:
      - https://raw.githubusercontent.com/sergelogvinov/proxmox-csi-plugin/main/docs/deploy/proxmox-csi-plugin-talos.yml
```

This manifest is where the `nodeSelector` is set:

```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: proxmox-csi-plugin-node
  namespace: csi-proxmox
  labels:
    helm.sh/chart: proxmox-csi-plugin-0.2.13
    app.kubernetes.io/name: proxmox-csi-plugin
    app.kubernetes.io/instance: proxmox-csi-plugin
    app.kubernetes.io/version: "v0.8.2"
    app.kubernetes.io/managed-by: Helm
...
      nodeSelector:
        node.cloudprovider.kubernetes.io/platform: nocloud
      tolerations:
        - operator: Exists
```

After the control plane and nodes were active, I then installed the Proxmox CCM using the `kubectl` method as described [here](https://github.com/sergelogvinov/proxmox-cloud-controller-manager/blob/main/docs/install.md). I chose the [full lifecycle management](https://github.com/sergelogvinov/proxmox-cloud-controller-manager/blob/main/docs/deploy/cloud-controller-manager.yml) so that the nodes would be managed properly (the talos-specific config did not label the nodes at all.) 

After this was applied, the nodes all got the following labels:

```
  labels:
    beta.kubernetes.io/arch: amd64
    beta.kubernetes.io/instance-type: 24VCPU-32GB
    beta.kubernetes.io/os: linux
    extensions.talos.dev/iscsi-tools: v0.1.5
    extensions.talos.dev/qemu-guest-agent: 9.1.0
    failure-domain.beta.kubernetes.io/region: dell-cluster
    failure-domain.beta.kubernetes.io/zone: r720
    kubernetes.io/arch: amd64
    kubernetes.io/hostname: talos-node-1
    kubernetes.io/os: linux
    node.cloudprovider.kubernetes.io/platform: nocloud
    node.kubernetes.io/instance-type: 24VCPU-32GB
    topology.kubernetes.io/region: dell-cluster
    topology.kubernetes.io/zone: r720
```


 
> Thanks.

Thank you for paying attention to the feedback! I've run across many who do not. It makes me want to help with the project.
