### ISSUE TITLE
Per node configuration mapping of proxmox storage for each kubernetes storage class

### ISSUE THREAD

**Issue by mentos1386** [sergelogvinov/proxmox-csi-plugin#297]
## Feature Request

My Proxmox cluster is of "throw together what you have" variety. Which resulted in nodes that have mostly unique storage configuration (and naming).

Example:
```
┌──────────────┐  ┌──────────────┐  ┌──────────────┐   ┌────────────────┐
│              │  │              │  │              │   │                │
│    NODE 1    │  │    NODE 2    │  │    NODE 3    │   │    NODE 4      │
│              │  │              │  │              │   │                │
│    local     │  │    local     │  │    local     │   │    local       │
│  local-nvme  │  │  local-nvme  │  │              │   │ local-nvme-lvm │
│  local-ssd   │  │              │  │              │   │                │
│              │  │              │  │              │   │                │
└──────────────┘  └──────────────┘  └──────────────┘   └────────────────┘
```

With current version of `proxmox-csi-plugin`.  I would have to create a different storage for each proxmox storage. And then be careful when scheduling workload to specify correct storage class for each node.

What I would want, is an "overlay" storage configuration. To specify an kubernetes storage class named "my-storage". And then somehow specify to what proxmox storage that maps for each node. **To have one kubernetes storage class map to different proxmox storages depending on the node.**

This could be done with current `parameters` option of the `StorageClass` but that would be hard to maintain, as nodes can be added/removed often.

Another option would be to define a CRD like `StorageNodeConfig` that would have the mapping for the node.

### How potential configuration could look like
```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: proxmox-default
parameters:
  csi.storage.k8s.io/fstype: xfs|ext4
  cache: directsync|none|writeback|writethrough
  ssd: "true|false"
provisioner: csi.proxmox.sinextra.dev
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: csi.proxmox.sinextra.dev/v1alpha1
kind: StorageNodeConfig
metadata:
  name: node-1
spec:
  nodeSelector:
    matchLabels:
      topology.kubernetes.io/zone: "node-1"
  available:
    - storageclass: proxmox-default
      proxmoxstorage: local-nvme
---
apiVersion: csi.proxmox.sinextra.dev/v1alpha1
kind: StorageNodeConfig
metadata:
  name: node-2
spec:
  nodeSelector:
    matchLabels:
      topology.kubernetes.io/zone: "node-2"
  available:
    - storageclass: proxmox-default
      proxmoxstorage: local-nvme
---
apiVersion: csi.proxmox.sinextra.dev/v1alpha1
kind: StorageNodeConfig
metadata:
  name: node-3
spec:
  nodeSelector:
    matchLabels:
      topology.kubernetes.io/zone: "node-3"
  available:
    - storageclass: proxmox-default
      proxmoxstorage: local
---
apiVersion: csi.proxmox.sinextra.dev/v1alpha1
kind: StorageNodeConfig
metadata:
  name: node-4
spec:
  nodeSelector:
    matchLabels:
      topology.kubernetes.io/zone: "node-4"
  available:
    - storageclass: proxmox-default
      proxmoxstorage: local-nvme-lvm
```

The `StorageNodeConfig` is inspired by Cilium's [CiliumNodeConfig](https://docs.cilium.io/en/latest/configuration/per-node-config/).

Due to the use of `nodeSelector` the configuration doesn't have to be "per node" but we could label nodes with `my.cluster/has-nvme: true` and then apply configuration for all nodes that have "nvme" etc.

### End goal?

To create PVC using storage class `proxmox-default` and that work across all nodes, by CSI picking whichever proxmox storage is configured for that particular node.

### Community Note

* Please vote on this issue by adding a 👍 reaction to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request

**Comment by sergelogvinov** [comment]
Hello! Interesting idea, thanks.

I've been thinking about the same thing the last few weeks. I’ve done some implementation in my private repo. I plan to open it in mid-January.

**Comment by sergelogvinov** [comment]
Hi, could you please take a look at my idea/implementation for the storage class selector?
https://github.com/sergelogvinov/hybrid-csi-plugin

**Comment by mentos1386** [comment]
Ooh awesome! I love that you can even mix different csi providers!

If i understand correctly, i would have to do something like:
```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: proxmox-node-1
parameters:
  csi.storage.k8s.io/fstype: xfs|ext4
  cache: directsync|none|writeback|writethrough
  ssd: "true|false"
provisioner: csi.proxmox.sinextra.dev
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
# Only on node-1
allowedTopologies:
- matchLabelExpressions:
  - key: topology.kubernetes.io/zone
    values:
    - node-1
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: proxmox-node-2
parameters:
  csi.storage.k8s.io/fstype: xfs|ext4
  cache: directsync|none|writeback|writethrough
  ssd: "true|false"
provisioner: csi.proxmox.sinextra.dev
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
# Only on node-2
allowedTopologies:
- matchLabelExpressions:
  - key: topology.kubernetes.io/zone
    values:
    - node-2
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: proxmox-hybrid
parameters:
  storageClasses: proxmox-node-1,proxmox-node-2
provisioner: csi.hybrid.sinextra.dev
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
```

And then use `proxmox-hybrid` as my storage class for volumes?

**Comment by sergelogvinov** [comment]
probably yes

```
kubectl get CSINode -ocustom-columns=NODE:.metadata.name,DRV:.spec.drivers
```

Based on the node name, It chooses the appropriate StorageClass. I have not tried using allowedTopologies yet.

**Comment by sergelogvinov** [comment]
https://github.com/sergelogvinov/hybrid-csi-plugin/issues/7

**Comment by sergelogvinov** [comment]
It should work with zone/region labels only (proxmox csi limitation)

```yaml
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: proxmox-node-2
parameters:
  csi.storage.k8s.io/fstype: xfs|ext4
  cache: directsync|none|writeback|writethrough
  ssd: "true|false"
provisioner: csi.proxmox.sinextra.dev
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
# Only on node-2, cluster-1
allowedTopologies:
- matchLabelExpressions:
  - key: topology.kubernetes.io/region
    values:
    - cluster-1
  - key: topology.kubernetes.io/zone
    values:
    - node-2
```
