### ISSUE TITLE
StorageClass annotations

### ISSUE THREAD

**Issue by JustScreaMy** [sergelogvinov/proxmox-csi-plugin#325]
## Feature Request
It would be nice, if I was able to add annotations to the `StorageClass` generated by helm, because for example I would like to be able to make this the default StorageClass, which should be done by annotation
`stirageclass.kubernetes.io/is-default-class: true`

### Community Note

* Please vote on this issue by adding a 👍 reaction to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request

**Comment by sergelogvinov** [comment]
Hi, I believe it already exists. Oh, we lost the documentation about it.

https://github.com/sergelogvinov/proxmox-csi-plugin/blob/main/charts/proxmox-csi-plugin/templates/storageclass.yaml

```yaml
storageClass:
  - name: proxmox-data-xfs
    storage: data
    annotations:
      stirageclass.kubernetes.io/is-default-class: true
```
