### ISSUE TITLE
Can this be used on a standalone node?

### ISSUE THREAD

**Issue by nipeharefa** [sergelogvinov/proxmox-csi-plugin#328]
Hi, I would like to know if this plugin can be used on a standalone node, or does it require a Proxmox cluster setup to work? Thank you for your help!

**Comment by sergelogvinov** [comment]
Yes it works perfect in one node setup (with/without proxmox cluster)

**Comment by nipeharefa** [comment]
okey @sergelogvinov , is there any difference between a Proxmox cluster and a single node?
https://github.com/sergelogvinov/proxmox-csi-plugin/blob/main/docs/install.md#install-the-plugin-by-using-kubectl.

**Comment by nipeharefa** [comment]
I used Helm to install it.
and values.yml is 
```
clusters:
  - url: https://host:8006/api2/json
    insecure: false
    token_id: "root@pam!nipe"
    token_secret: "uuidtoken"
    region: jkt


existingConfigSecret: proxmox-csi-plugin

```
and from the controller logger, I got error 
```

1 controller.go:593] "GetCapacity: failed to get proxmox cluster" err="proxmox cluster Region-1 not found" cluster="Region-1"
E0219 03:57:49.187542       1 main.go:101] "GRPC error" err="rpc error: code = Internal desc = proxmox cluster Region-1 not found"
```
