### ISSUE TITLE
Typo in Helm Values for Annotation

### ISSUE THREAD

**Issue by kuan51** [sergelogvinov/proxmox-csi-plugin#339]
### Description

There is a typo in the helm values for the annotation `storageclass.kubernetes.io/is-default-class` on this [page](https://github.com/sergelogvinov/proxmox-csi-plugin/blob/main/docs/install.md). Need to change `stirageclass` to `storageclass`.

The current helm value:

```
# Define the storage classes
storageClass:
    ...
    annotations:
      stirageclass.kubernetes.io/is-default-class: "true"
```

The correct helm value:

```
# Define the storage classes
storageClass:
    ...
    annotations:
      storageclass.kubernetes.io/is-default-class: "true"
```

### Logs

Not applicable

### Environment

Not applicable

### Community Note

* Please vote on this issue by adding a 👍 reaction to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
