### ISSUE TITLE
CSI won't handle resize of pvc

### ISSUE THREAD

**Issue by markussiebert** [sergelogvinov/proxmox-csi-plugin#370]
## Bug Report

Trying to resize a pvc, but csi won't handle:

```yaml
Name:          some-postgres-1                                                                                                                                                                                                                                                                                                                                                                                
Namespace:     app-some                                                                                                                                                                                                                                                                                                                                                                                       
StorageClass:  proxmox-data-xfs                                                                                                                                                                                                                                                                                                                                                                                 
Status:        Bound                                                                                                                                                                                                                                                                                                                                                                                            
Volume:        pvc-811e63d1-45e3-4987-a14c-72f359960887                                                                                                                                                                                                                                                                                                                                                         
Labels:        cnpg.io/cluster=some-postgres                                                                                                                                                                                                                                                                                                                                                                  
               cnpg.io/instanceName=some-postgres-1                                                                                                                                                                                                                                                                                                                                                           
               cnpg.io/instanceRole=primary                                                                                                                                                                                                                                                                                                                                                                     
               cnpg.io/pvcRole=PG_DATA                                                                                                                                                                                                                                                                                                                                                                          
               role=primary                                                                                                                                                                                                                                                                                                                                                                                     
Annotations:   cnpg.io/nodeSerial: 1                                                                                                                                                                                                                                                                                                                                                                            
               cnpg.io/operatorVersion: 1.26.0                                                                                                                                                                                                                                                                                                                                                                  
               cnpg.io/pvcStatus: ready                                                                                                                                                                                                                                                                                                                                                                         
               pv.kubernetes.io/bind-completed: yes                                                                                                                                                                                                                                                                                                                                                             
               pv.kubernetes.io/bound-by-controller: yes                                                                                                                                                                                                                                                                                                                                                        
               volume.beta.kubernetes.io/storage-provisioner: csi.proxmox.sinextra.dev                                                                                                                                                                                                                                                                                                                          
               volume.kubernetes.io/selected-node: talos-production                                                                                                                                                                                                                                                                                                                                             
               volume.kubernetes.io/storage-provisioner: csi.proxmox.sinextra.dev                                                                                                                                                                                                                                                                                                                               
Finalizers:    [kubernetes.io/pvc-protection]                                                                                                                                                                                                                                                                                                                                                                   
Capacity:      16Gi                                                                                                                                                                                                                                                                                                                                                                                             
Access Modes:  RWO                                                                                                                                                                                                                                                                                                                                                                                              
VolumeMode:    Filesystem                                                                                                                                                                                                                                                                                                                                                                                       
Used By:       some-postgres-1                                                                                                                                                                                                                                                                                                                                                                                
Events:                                                                                                                                                                                                                                                                                                                                                                                                         
  Type     Reason             Age   From           Message                                                                                                                                                                                                                                                                                                                                                      
  ----     ------             ----  ----           -------                                                                                                                                                                                                                                                                                                                                                      
  Warning  ExternalExpanding  59m   volume_expand  waiting for an external controller to expand this PVC  
```

### Description
The volume won't resize ... 

### Logs

I can see the volume in the logs in a line sarting with:

```
csi-provisioner I0529 17:05:46.698610       1 controller.go:1171] "handleProtectionFinalizer"
````

No other mentions of that pvc ... and no resize 

### Environment

- Plugin version:
- Kubernetes version:
```
Client Version: v1.32.3
Kustomize Version: v5.5.0
Server Version: v1.32.3
```
- CSI capasity:
```
proxmox-data-xfs   41267203408   map[topology.kubernetes.io/region:pve topology.kubernetes.io/zone:pve]
```

### Community Note

* Please vote on this issue by adding a 👍 reaction to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request

**Comment by sergelogvinov** [comment]
Hello,

It would be best to start by collecting the logs. The resize process involves two containers within the proxmox-csi-plugin-controller pod: `csi-resizer` and `proxmox-csi-plugin-controller`. Please check the logs for both containers. If the logs don’t provide enough detail, consider increasing the verbosity level by adding `-v=5`.

Thank you!

**Comment by tamcore** [comment]
I've attached log files for both containers. But they don't seem to show anything useful.

The first attempt to resize `test-pvc` somehow succeeded. Continued attempts, just didn't. 

[csi-resizer.log](https://github.com/user-attachments/files/20541643/csi-resizer.log)
[proxmox-csi-controller.log](https://github.com/user-attachments/files/20541642/proxmox-csi-controller.log)

**Comment by sergelogvinov** [comment]
Hello, 
I found the logs

```
proxmox-csi-controller-7fcdb8fcd5-66f9l proxmox-csi-controller I0601 17:31:35.726473       1 controller.go:757] "ControllerExpandVolume: volume expanded" cluster="home" volumeID="home/pve/tank/vm-9999-pvc-c10754fc-eb36-4c2e-8ef9-bd83914eb247" vmID=1006 size=2147483648
```

Can you check if the PV pv=vm-9999-pvc-c10754fc-eb36-4c2e-8ef9-bd83914eb247 had its size changed?

**Comment by tamcore** [comment]
Unfortunately not. No change on the PV, or even the status of the PVC. 

Currently it also looks like
```yaml
---
kind: PersistentVolumeClaim
spec:
  resources:
    requests:
      storage: 3Gi
status:
  allocatedResourceStatuses:
    storage: NodeResizePending
  allocatedResources:
    storage: 2Gi
  capacity:
    storage: 2Gi
---
kind: PersistentVolume
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 2Gi
```
and the only `Event` in the namespace is also just
```
80s         Normal    ExternalExpanding              persistentvolumeclaim/test-pvc   waiting for an external controller to expand this PVC
```
without anything else in the logs.
